image: rust:latest

stages:
  - build
  - test
  - run

before_script:
  - rustc --version
  - cargo --version

build:
  stage: build
  script:
    - cargo build --verbose

test:
  stage: test
  script:
    - cargo test --verbose

run:
  stage: run
  script:
    - cargo run
