#!/bin/bash

# Script to assemble and run x86 assembly files generated by the WLP4 compiler
# Usage: ./run_x86.sh <filename.x86>

if [ $# -eq 0 ]; then
    echo "Usage: $0 <filename.x86>"
    echo "Example: $0 @completed/hello_world.x86"
    exit 1
fi

X86_FILE="$1"
BASENAME=$(basename "$X86_FILE" .x86)
OUTPUT_DIR="executables"

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "=== Assembling and Running x86 Assembly ==="
echo "Input file: $X86_FILE"
echo "Output directory: $OUTPUT_DIR"

# Check if NASM is installed
if ! command -v nasm &> /dev/null; then
    echo "Error: NASM (Netwide Assembler) is not installed."
    echo "Install it with: sudo apt install nasm"
    exit 1
fi

# Check if gcc is installed
if ! command -v gcc &> /dev/null; then
    echo "Error: GCC is not installed."
    echo "Install it with: sudo apt install gcc"
    exit 1
fi

echo "Step 1: Assembling x86 assembly to object file..."
nasm -f elf32 "$X86_FILE" -o "$OUTPUT_DIR/$BASENAME.o"

if [ $? -ne 0 ]; then
    echo "Error: Assembly failed!"
    exit 1
fi

echo "Step 2: Linking object file to create executable..."
gcc -m32 "$OUTPUT_DIR/$BASENAME.o" -o "$OUTPUT_DIR/$BASENAME"

if [ $? -ne 0 ]; then
    echo "Error: Linking failed!"
    exit 1
fi

echo "Step 3: Running the executable..."
echo "=== Program Output ==="
"$OUTPUT_DIR/$BASENAME"

echo ""
echo "=== Execution Complete ==="
echo "Executable created: $OUTPUT_DIR/$BASENAME"
echo "You can run it again with: $OUTPUT_DIR/$BASENAME"
